# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: fa9d69d6ef6230ad4277650eeec93c7d71d6bedcb184600d4fa80c5ab052d856425596da2cc476ee4d937f0f8a11686b0e7aa49e720e01a8727b5dcf53ef8341

test:
  domain_name: example.com 
  secret_key_base: 3537c98c9a587ca8fc207bbbee4cf2b117f566a49bfcfe8c84b37ce3e84c0044c6546936c5f92f36257eedb908c91e82ab9b3cdb6d1e2cf57e3d83dc731a6beb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
